-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 16:01:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locadora` (
  `CNPJ` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  `Num` INT NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_locadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_locadora` (
  `Locadora_CNPJ` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`Telefone`, `Locadora_CNPJ`),
  CONSTRAINT `fk_Telefones_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `Titulo` VARCHAR(45) NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `Locadora_CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Titulo`, `Codigo`),
  CONSTRAINT `fk_Filme_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Filme_Locadora1_idx` ON `mydb`.`Filme` (`Locadora_CNPJ` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `CPF` VARCHAR(45) NOT NULL,
  `Locadora_CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_Funcionario_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Funcionario_Locadora1_idx` ON `mydb`.`Funcionario` (`Locadora_CNPJ` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  `Num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Funcionario_CPF`),
  CONSTRAINT `fk_Gerente_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gerente_Funcionario1_idx` ON `mydb`.`Gerente` (`Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`telefone_gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_gerente` (
  `Gerente_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`Gerente_Funcionario_CPF`, `Telefone`),
  CONSTRAINT `fk_Telefones_Gerente1`
    FOREIGN KEY (`Gerente_Funcionario_CPF`)
    REFERENCES `mydb`.`Gerente` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefones_Gerente1_idx` ON `mydb`.`telefone_gerente` (`Gerente_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`emails_gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails_gerente` (
  `Gerente_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Email2` VARCHAR(45) NULL,
  `Email3` VARCHAR(45) NULL,
  PRIMARY KEY (`Gerente_Funcionario_CPF`, `Email`),
  CONSTRAINT `fk_Emails_Gerente1`
    FOREIGN KEY (`Gerente_Funcionario_CPF`)
    REFERENCES `mydb`.`Gerente` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Emails_Gerente1_idx` ON `mydb`.`emails_gerente` (`Gerente_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Estoquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoquista` (
  `Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  `Num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Funcionario_CPF`),
  CONSTRAINT `fk_Estoquista_Funcionario1`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caixa` (
  `Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  `Num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Funcionario_CPF`),
  CONSTRAINT `fk_Estoquista_Funcionario10`
    FOREIGN KEY (`Funcionario_CPF`)
    REFERENCES `mydb`.`Funcionario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emails_estoquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails_estoquista` (
  `Estoquista_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Email2` VARCHAR(45) NULL,
  `Email3` VARCHAR(45) NULL,
  PRIMARY KEY (`Estoquista_Funcionario_CPF`, `Email`),
  CONSTRAINT `fk_Emails_copy1_Estoquista1`
    FOREIGN KEY (`Estoquista_Funcionario_CPF`)
    REFERENCES `mydb`.`Estoquista` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Emails_copy1_Estoquista1_idx` ON `mydb`.`emails_estoquista` (`Estoquista_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`telefone_estoquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_estoquista` (
  `Estoquista_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`Estoquista_Funcionario_CPF`, `Telefone`),
  CONSTRAINT `fk_Telefones_copy1_Estoquista1`
    FOREIGN KEY (`Estoquista_Funcionario_CPF`)
    REFERENCES `mydb`.`Estoquista` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefones_copy1_Estoquista1_idx` ON `mydb`.`telefone_estoquista` (`Estoquista_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`emails_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails_caixa` (
  `Caixa_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Email2` VARCHAR(45) NULL,
  `Email3` VARCHAR(45) NULL,
  PRIMARY KEY (`Caixa_Funcionario_CPF`, `Email`),
  CONSTRAINT `fk_Emails_Caixa1`
    FOREIGN KEY (`Caixa_Funcionario_CPF`)
    REFERENCES `mydb`.`Caixa` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Emails_Caixa1_idx` ON `mydb`.`emails_caixa` (`Caixa_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`telefone_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_caixa` (
  `Caixa_Funcionario_CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`Caixa_Funcionario_CPF`, `Telefone`),
  CONSTRAINT `fk_Telefones_Caixa1`
    FOREIGN KEY (`Caixa_Funcionario_CPF`)
    REFERENCES `mydb`.`Caixa` (`Funcionario_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefones_Caixa1_idx` ON `mydb`.`telefone_caixa` (`Caixa_Funcionario_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Copia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Copia` (
  `Filme_Codigo` VARCHAR(45) NOT NULL,
  `Filme_Titulo` VARCHAR(45) NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  `Data_Emprestimo` VARCHAR(45) NOT NULL,
  `Data_Devolucao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Filme_Codigo`),
  CONSTRAINT `fk_Copia_Filme1`
    FOREIGN KEY (`Filme_Titulo` , `Filme_Codigo`)
    REFERENCES `mydb`.`Filme` (`Titulo` , `Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Copia_Filme1_idx` ON `mydb`.`Copia` (`Filme_Titulo` ASC, `Filme_Codigo` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`d_funcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`d_funcional` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `Cliente_CPF` VARCHAR(45) NOT NULL,
  `d_funcional_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cliente_CPF`),
  CONSTRAINT `fk_Dependente_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dependente_d_funcional1`
    FOREIGN KEY (`d_funcional_cpf`)
    REFERENCES `mydb`.`d_funcional` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Dependente_d_funcional1_idx` ON `mydb`.`Dependente` (`d_funcional_cpf` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Titular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titular` (
  `Cliente_CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  PRIMARY KEY (`Cliente_CPF`),
  CONSTRAINT `fk_Titular_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Titular_Cliente1_idx` ON `mydb`.`Titular` (`Cliente_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`telefone_dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_dependente` (
  `d_funcional_cpf` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`d_funcional_cpf`, `Telefone`),
  CONSTRAINT `fk_telefone_dependente_d_funcional1`
    FOREIGN KEY (`d_funcional_cpf`)
    REFERENCES `mydb`.`d_funcional` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_dependente_d_funcional1_idx` ON `mydb`.`telefone_dependente` (`d_funcional_cpf` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`emails_dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails_dependente` (
  `d_funcional_cpf` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Email2` VARCHAR(45) NULL,
  `Email3` VARCHAR(45) NULL,
  PRIMARY KEY (`d_funcional_cpf`, `Email`),
  CONSTRAINT `fk_emails_dependente_d_funcional1`
    FOREIGN KEY (`d_funcional_cpf`)
    REFERENCES `mydb`.`d_funcional` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emails_dependente_d_funcional1_idx` ON `mydb`.`emails_dependente` (`d_funcional_cpf` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`emails_titular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails_titular` (
  `Titular_Cliente_CPF` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Email2` VARCHAR(45) NULL,
  `Email3` VARCHAR(45) NULL,
  PRIMARY KEY (`Titular_Cliente_CPF`, `Email`),
  CONSTRAINT `fk_Emails_Titular1`
    FOREIGN KEY (`Titular_Cliente_CPF`)
    REFERENCES `mydb`.`Titular` (`Cliente_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Emails_Titular1_idx` ON `mydb`.`emails_titular` (`Titular_Cliente_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`telefone_titular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_titular` (
  `Titular_Cliente_CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  `Telefone3` VARCHAR(45) NULL,
  PRIMARY KEY (`Titular_Cliente_CPF`, `Telefone`),
  CONSTRAINT `fk_Telefones_Titular1`
    FOREIGN KEY (`Titular_Cliente_CPF`)
    REFERENCES `mydb`.`Titular` (`Cliente_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefones_Titular1_idx` ON `mydb`.`telefone_titular` (`Titular_Cliente_CPF` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo` (
  `ID` VARCHAR(45) NOT NULL,
  `Copia_Filme_Codigo` VARCHAR(45) NOT NULL,
  `Cliente_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Emprestimo_Copia1`
    FOREIGN KEY (`Copia_Filme_Codigo`)
    REFERENCES `mydb`.`Copia` (`Filme_Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Emprestimo_Copia1_idx` ON `mydb`.`Emprestimo` (`Copia_Filme_Codigo` ASC);

CREATE INDEX `fk_Emprestimo_Cliente1_idx` ON `mydb`.`Emprestimo` (`Cliente_CPF` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
